{% set name = "fastapi-users-db-sqlalchemy" %}
{% set version = "4.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d223742e687cf386bea4e990d6ca8571185c50f365301a34e8eb14ebbda18b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - fastapi-users >=9.1.0
    - sqlalchemy >=1.4

test:
  imports:
    - fastapi_users_db_sqlalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users-db-sqlalchemy
  summary: FastAPI Users - Database adapter for SQLAlchemy + encode/databases
  doc_url: https://fastapi-users.github.io/fastapi-users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
