{% set name = "fastapi-users-db-sqlalchemy" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 347c709ebb5963ed475f8c671166717d8e47897dec595ede02a95a8f607fa1ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - hatchling
    - hatch-regex-commit
    - python >=3.8
  run:
    - python >=3.8
    - fastapi-users >=10.0.0
    - sqlalchemy >=2.0.0,<2.1.0

test:
  imports:
    - fastapi_users_db_sqlalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users-db-sqlalchemy
  summary: FastAPI Users - Database adapter for SQLAlchemy + encode/databases
  doc_url: https://fastapi-users.github.io/fastapi-users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
