{% set name = "fastapi-users-db-sqlalchemy" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29551c1babdfea3c964dc54aea5148431b066cdaea1dc44054a6e370368aee55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - fastapi-users >=9.1.0
    - sqlalchemy >=1.4

test:
  imports:
    - fastapi_users_db_sqlalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users-db-sqlalchemy
  summary: FastAPI Users - Database adapter for SQLAlchemy + encode/databases
  doc_url: https://fastapi-users.github.io/fastapi-users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
