{% set name = "fastapi-users-db-sqlalchemy" %}
{% set version = "5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 013c2800ce1cb5149acbd1d7eb8596e4aa7dd578395c40df951b666a121388c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - hatchling
    - hatch-regex-commit
    - python >=3.7
  run:
    - python >=3.7
    - fastapi-users >=10.0.0
    - sqlalchemy >=1.4,<2.0.0

test:
  imports:
    - fastapi_users_db_sqlalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users-db-sqlalchemy
  summary: FastAPI Users - Database adapter for SQLAlchemy + encode/databases
  doc_url: https://fastapi-users.github.io/fastapi-users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
